# Site settings
title: "phuud's Blog"
email: jacob@jacobtomlinson.co.uk
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A dark flame master"
title_image: "public/img/img01.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: zuxic
github_username: phuud
linkedin_link: http://bgm.tv/
google_plus_link: http://bilibili.tv/
stackoverflow_link: http://weibo.com/

# Footer
footer_left: "Copyright &copy; 2015,<a href=\"http://twitter.com/zuxic\">Phuud Wang</a>.Hosted by <i class=\"fa fa-github-alt\"></i> <a href=\"https://github.com\"><b>GitHub</b></a>."
footer_right: "Powered by <a href=\"http://github.com/mojombo/jekyll\"target='_blank'><b>Jekyll</b></a> and <a href=\"https://github.com/jacobtomlinson/carte-noire\"target='_blank'><b>Jacob Tomlinson</b></a>."

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
